/** Shared explanations for the existing controls and statistics. */
export const descriptions: Record<string, string> = {
  reference: "A positive price you choose for this product. 10000 is only a starting example, not an inferred fair value or settlement price.",
  fixed_deviation: "Mid minus your reference price, in price units. Negative means below reference; positive means above. Choose a reference appropriate to this product.",
  sma_deviation: "Mid minus its trailing simple moving average, in price units. Includes the current snapshot; blank until a complete window exists. Negative means below the recent average.",
  ema_deviation: "Mid minus its trailing exponential moving average, in price units. Recent observations carry more weight (alpha = 2 / (window + 1)). Starts after window valid prices; missing prices remain blank without advancing the EMA.",
  microprice_gap: "Microprice minus mid, in price units. Positive indicates bid-side book pressure; negative indicates ask-side pressure. This is a book signal, not guaranteed profit.",
  microprice: "Book-volume-weighted price. More bid volume pulls it toward the ask; this is a pressure estimate, not a guaranteed fair value.",
  sma: "Simple moving average of mid over the chosen snapshots. Smooths movement and stays blank until a complete window is available.",
  vwap: "Executed trade prices weighted by quantity, accumulated across selected days. Blank until the first trade.",
  spread: "Best ask minus best bid in price units: the gap between immediately buying and selling.",
  imbalance: "(Best-bid volume − best-ask volume) / total top-level volume. +1 means buy-side depth dominates; −1 means sell-side depth dominates. It does not guarantee a move.",
  returns: "Fractional mid-price change from the previous snapshot. 0.01 means +1%; missing prices remain gaps.",
  zscore: "Distance from the rolling mid average in standard deviations. +2 means two deviations above average; −2 means two below.",
  rolling_vol: "Sample standard deviation of snapshot returns over the chosen window. Larger means more fluctuation. Not annualized.",
  n_snapshots: "Loaded order-book snapshots across selected days, including rows with missing prices.",
  n_trades: "Number of executions. Each trade may exchange multiple units.",
  volume: "Total units exchanged, summed over recorded trades.",
  mid_range: "Lowest and highest valid mid prices in the selected data.",
  mid_mean: "Average valid mid across selected snapshots. Missing prices are excluded.",
  mid_std: "Standard deviation of price levels in price units. Includes changes between days; different from return volatility.",
  spread_mean: "Average best-ask minus best-bid spread where both sides exist.",
  spread_range: "Smallest and largest spread where both sides of the book exist.",
  count: "Matching snapshots with a valid future price. Adjacent matches may describe the same move.",
  signal_rate: "Matches divided by snapshots with a usable signal and future price. Excludes warm-up and the tail beyond the horizon.",
  hit_rate: "Percentage of matches followed by a higher mid price. Lower values may support a bearish signal; this is not an executed strategy's win rate.",
  mean: "Average fractional mid-price change after the condition matches. Fills and terminal settlement are not simulated.",
  median: "Middle event return: half the outcomes lie on either side.",
  percentiles: "10th and 90th percentile event returns. Roughly 80% of observed outcomes lie between them.",
  bootstrap: "95% interval from resampling matching snapshots. Adjacent signals can describe the same move; compare the day breakdown too.",
  horizon: "Future snapshots used to measure the price response. Continues across selected days; this is not a settlement deadline.",
  threshold: "Value compared with the indicator. Units depend on the signal: returns use fractions, imbalance and z-score are unitless.",
  window: "Number of snapshots in a rolling calculation. Larger windows smooth more history and need longer to warm up.",
  scope: "The top selectors choose season, round, and days. This control chooses products or a saved synthetic dataset.",
  split: "Earlier selected days versus the last day. Earlier-day outcomes entering the last day are excluded. Repeated tuning on the last day weakens its independence.",
  distribution: "Counts of matching future returns in each interval. The horizontal axis is fractional return.",
  orderbook: "Up to three price levels on each side at the hovered snapshot. Bids are buying interest; asks are selling interest.",
  eventwindow: "Quickly measure what happened after an indicator condition, using the chart's window settings.",
  autocorr_lag1: "Correlation between consecutive price changes. Positive suggests continuation; negative suggests alternation. Zero is also used when too few changes exist.",
  mid_min: "Lowest valid mid price.", mid_max: "Highest valid mid price.",
};
